### ISSUE TITLE
Dualhooked

### ISSUE THREAD

**Issue by glosifyed** [dekrypted/image-logger#2]
Why Is There "|JeWF01!$>Nk#wx0RaF=07w7;|JwjV0RR90|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|Nq+nLjnK)|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsBO01*fQ-~r$R0TBQK5di}c0sq7R6aWDL00000000000000000030!~hfl0RR910000000000000000RP$m3<CiG0uTcb00031000000000000000000000000000" I Couldnt Decode It But I Am 100% Sure That Its Dualhooked

**Comment by dekrypted** [comment]
Please understand/read the code before making these claims.

First of all, you can clearly see it's base85 decoding it, so base85 decode it! 🧠💡
Second of all, read the code. It's writing that binary to the webpage... Writing binary to the webpage? That must be an image!

Lastly, it's literally named "buggedbin," it's the loading discord image. If you don't want to use my tool because you're too lazy to understand the code, feel free. But don't make these false claims with literally no knowledge. I'd suggest you learn how to code 😄

**Comment by glosifyed** [comment]
> 

Ok Then how do i decode it, i tried every website but its a invaild input

**Comment by dekrypted** [comment]
💀
